include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"
    - "**/build/**"
    - "ios/Flutter/**"
    - "android/**"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    # Strong correctness
    unrelated_type_equality_checks: error
    missing_required_param: error
    missing_return: error

    # Code quality
    avoid_print: error
    unnecessary_nullable_for_final_variable_declarations: warning
    prefer_const_constructors: warning
    use_build_context_synchronously: warning
    depend_on_referenced_packages: warning
    deprecated_member_use: warning

linter:
  rules:
    # Keep consistent with analyzer (avoid duplication conflicts)
    avoid_print: true
    prefer_const_constructors: true

    # Imports
    prefer_relative_imports: true
    always_use_package_imports: false

    # Const / immutability
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true

    # Clean code
    unnecessary_late: true
    use_super_parameters: true

    # Dependencies / streams
    sort_pub_dependencies: true
    cancel_subscriptions: true
    close_sinks: true
